### ISSUE TITLE
Fix code scanning alert - Missing rate limiting (1-3)

### ISSUE THREAD

**Issue by ReubenMathew** [ReubenMathew/HelpDesk#25]
Tracking issue for:
- [x] https://github.com/ReubenMathew/HelpDesk/security/code-scanning/2
- [ ] https://github.com/ReubenMathew/HelpDesk/security/code-scanning/124
- [ ] https://github.com/ReubenMathew/HelpDesk/security/code-scanning/125
- [ ] https://github.com/ReubenMathew/HelpDesk/security/code-scanning/126
- [ ] https://github.com/ReubenMathew/HelpDesk/security/code-scanning/127

**Comment by JohnStegmaier** [comment]
for Issue No. 2 - I have tested and confirmed the functionality of the rate limiter implemented in #28 to resolve this:
![Screenshot from 2022-03-26 20-05-23](https://user-images.githubusercontent.com/100036246/160261407-9b5ea78b-8d40-47ee-bbb3-ef39c3231b0b.png)
The above is a demonstration of the rate limiter preventing a malicious adversary from conducting a DDOS attack by spamming incorrect credentials. This also greatly reduces the chances of a brute force attack being successful in guessing a Username/Password combination.

**Comment by ReubenMathew** [comment]
Closed with #28
